# Generated by Django 2.0.9 on 2018-12-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
