# Generated by Django 2.0.9 on 2018-12-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_pics',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
    ]
