# Generated by Django 2.0.9 on 2018-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_auto_20181229_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_pic',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pic'),
        ),
    ]
